Tusharbajaj96/Attendance-Tracker

index.css, index.html
This PR introduces a fully responsive navigation bar for the Attendance Tracker website. It includes the following features:
✅ Fixed/Sticky Navbar – Ensures the navbar stays visible while scrolling.
✅ Responsive Design – Works across desktops, tablets, and mobile devices.
✅ Navigation Links – Includes Dashboard, Student Information, Mentor Info, Settings and Log out.
✅ Accessibility Improvements – Includes keyboard navigation and proper contrast for better UX.
Changes Made:
Implemented navbar structure using HTML & CSS.
Ensured responsiveness with CSS media queries.
Tested across multiple screen sizes for compatibility.
**How to Test:**
Run the project locally and open it in a web browser.
Check the navbar on different screen sizes.
Ensure the navbar styling aligns with the website's …
=> Added Responsive Navbar with Mobile Support

attendance.css, attendance.html
This pull request adds the sidebar navigation and top header section to the Attendance page.
✅ Included:
- Sidebar with menu links (Dashboard, Student Profile, Mentor Info, Attendance, Settings)
- Header with dashboard title, date, search bar, theme toggle, and user info
- Responsive layout using Flexbox
These components match the design used across the site for layout consistency.
This forms the base structure for continuing with chart and calendar integration.
=> Add Navbar and Header Section for Attendance Page

index.css, index.html
This pull request adds the HTML and CSS for student performance cards. 
**Features:**
- Student avatar and details section
- Performance feedback from teachers
- Star ratings for multiple categories
- Modern, clean, and responsive design
Tested on latest browsers for compatibility.
=> Add Student Performance Cards with Responsive UI

MENTOR.css, MENTOR.html
This PR introduces the top section of the Mentor Info page, including the mentor's image, name, gender, designation, department, email, and academic information such as expertise, subjects, research papers, and projects. The layout is clean and includes basic responsive styling.
=> Added top section of Mentor Info page with profile and academic details

student.html, style.css
This PR adds the static layout and styling for the Student Profile Page based on the provided design. It focuses on structuring the page using HTML and applying clean, modern CSS styling.
=> Designed Student Profile Page Layout (HTML + CSS)

index.css, index.html
This pull request includes the implementation of two key sections on the Dashboard page:
Course Statistics Section:
- Displays status cards for "Done", "On Progress", and "To Do"
- Uses progress bars to visually represent course completion levels
- Styled for responsiveness and clean layout
Attendance Summary Section:
- Shows total classes, present, and absent counts
- Displays overall attendance percentage
- Colored indicators for present (green), and absent (red)
- Includes support for future enhancements like dynamic charts
These updates improve the clarity and visual appeal of the attendance dashboard, making it easier to track academic progress and attendance at a glance.
=> Added Course Statistics and Attendance Summary Sections to Dashboard

attendance.css, attendance.html, attendance1.html, attendance_css.css
This pull request adds the main content area of the Attendance page, including:
Course statistics display box (Total, Present, Absent, and Percentage)
Conditional message based on attendance percentage
Structural layout using responsive divs
Initial styling for attendance cards and stat boxes
=> Added Inner Section for Attendance Page with Attendance Statistics Display

MENTOR.css, MENTOR.html
This pull request introduces a contact section to the Mentor page, enabling users to easily get in touch. Key features include:
Contact form with fields for email, and message.
Basic form validation and responsive design.
=> Add Contact Section to Mentor Page.

MENTOR.css, MENTOR.html
Integrated a new feedback section into the mentor page to allow users to share their thoughts and experiences.
=> Add Feedback Section to Mentor Page.

student.html, style.css
Created an Academic Performance box in the lower section with suitable icons and with each term report respectively.
=> Created an Academic Performance box.

MENTOR.css, MENTOR.html
Implemented the inner structure of the feedback section on the mentor page.
Added layout components to define the section’s structure.
Ensured styling aligns with the overall design of the mentor page.
=> Add Inner Section for Feedback on Mentor Page.

index.css, index.html
This PR adds a new Course Schedule section to the dashboard of the Attendance Tracker website. The section will display a list of scheduled classes including course name, date, time, and venue, allowing users to quickly view upcoming sessions.
=> Add The Course Schedule Section

MENTOR.css, MENTOR.html
Introduced a new query button within the feedback section of the mentor page.
Ensured the button styling aligns with existing UI components.
Positioned the button appropriately within the section layout.
=> Added Query Button to Mentor Page Feedback Section.

student.html, style.css
Created "Attendance box" in the lower section of the Student Profile page parallel to the Academic Performance.
=> Created Attendance box in the lower section.

student.html, style.css
Created  a 'Fee Status' section positioned below the Academic Performance box in the Student Profile. This section includes all necessary functional features, such as dynamically displaying the fee status for each academic quarter and indicating whether the fee is paid, pending, or if a receipt is available for download.
=> Created "Fee Status" Section below the Academic Performance box in Student Profile.

student.html, style.css
Created "Teacher's Remark" Section just below the 'Attendance' Section on the Student Profile Page.
It has the following functions:
Displays feedback provided by the class teacher .Along with Teacher’s Name, Remark Content, Star Rating (for behavior/academic performance) .
=> Created "Teacher's Remark" Section on Student Profile Page.

MENTOR.css, MENTOR.html
Reverts Tusharbajaj96/Attendance-Tracker#46
=> Revert "Added Query Button to Mentor Page Feedback Section."

mentor.css, mentor.html
This PR contains Header and Navbar contains all the required Functions of the Provided Issue.
=> Added the Code for Header and Navbar of the Mentor Page

mentor.css, mentor.html
This pull request introduces a new Mentor Information section to the project. The section includes structured HTML and styled CSS to display mentor profiles in a clean, responsive layout. Key features include:
Structured layout for mentor names, roles, and brief bios.
Responsive design for various screen sizes.
Styling consistent with the overall site theme.
=> Added Mentor Information Section to Project.

mentor.css, mentor.html
Structured HTML layout for contact details (e.g., email, phone, social links, or form if applicable).
Clean and responsive CSS styling consistent with the overall page design.
Enhanced accessibility and user experience for contacting mentors.
=>  Add Contact Section to Mentor Page (HTML & CSS).
